version: '2'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: docker-mongo
    expose:        
      - 27017

  spring:
    image: moviecruiser-app
    build: Movie-Cruiser-App/
    restart: always
    network_mode: host
    container_name: spring-docker
    depends_on: 
      - mongo
    ports:
      - "8080:8080"
    expose:        
      - 8080
  
